// THIS FILE WILL BE REGENERATED by `pnpm db:types` once migrations are applied.
// It exists as a hand-crafted approximation so Phase 2+ code typechecks before db push.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      clinics: {
        Row: {
          id: string
          name: string
          legal_name: string | null
          cif: string | null
          address: string | null
          city: string | null
          postal_code: string | null
          country: string
          timezone: string
          phone: string | null
          email: string | null
          logo_url: string | null
          dpo_contact: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          legal_name?: string | null
          cif?: string | null
          address?: string | null
          city?: string | null
          postal_code?: string | null
          country?: string
          timezone?: string
          phone?: string | null
          email?: string | null
          logo_url?: string | null
          dpo_contact?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          legal_name?: string | null
          cif?: string | null
          address?: string | null
          city?: string | null
          postal_code?: string | null
          country?: string
          timezone?: string
          phone?: string | null
          email?: string | null
          logo_url?: string | null
          dpo_contact?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      clinic_members: {
        Row: {
          id: string
          clinic_id: string
          user_id: string
          role: Database["public"]["Enums"]["member_role"]
          is_active: boolean
          invited_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          user_id: string
          role: Database["public"]["Enums"]["member_role"]
          is_active?: boolean
          invited_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          user_id?: string
          role?: Database["public"]["Enums"]["member_role"]
          is_active?: boolean
          invited_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "clinic_members_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          }
        ]
      }
      clinic_invitations: {
        Row: {
          id: string
          clinic_id: string
          email: string
          role: Database["public"]["Enums"]["member_role"]
          token: string
          expires_at: string
          accepted_at: string | null
          invited_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          email: string
          role: Database["public"]["Enums"]["member_role"]
          token: string
          expires_at: string
          accepted_at?: string | null
          invited_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          email?: string
          role?: Database["public"]["Enums"]["member_role"]
          token?: string
          expires_at?: string
          accepted_at?: string | null
          invited_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "clinic_invitations_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          }
        ]
      }
      professionals: {
        Row: {
          id: string
          clinic_id: string
          user_id: string
          license_number: string | null
          specialty: string | null
          display_name: string
          color: string
          default_appointment_minutes: number
          weekly_schedule: Json
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          user_id: string
          license_number?: string | null
          specialty?: string | null
          display_name: string
          color?: string
          default_appointment_minutes?: number
          weekly_schedule?: Json
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          user_id?: string
          license_number?: string | null
          specialty?: string | null
          display_name?: string
          color?: string
          default_appointment_minutes?: number
          weekly_schedule?: Json
          is_active?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "professionals_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          }
        ]
      }
      rooms: {
        Row: {
          id: string
          clinic_id: string
          name: string
          kind: Database["public"]["Enums"]["room_kind"]
          capacity: number
          color: string
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          name: string
          kind?: Database["public"]["Enums"]["room_kind"]
          capacity?: number
          color?: string
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          name?: string
          kind?: Database["public"]["Enums"]["room_kind"]
          capacity?: number
          color?: string
          is_active?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "rooms_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          }
        ]
      }
      service_types: {
        Row: {
          id: string
          clinic_id: string
          name: string
          duration_minutes: number
          color: string
          price_cents: number | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          name: string
          duration_minutes: number
          color?: string
          price_cents?: number | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          name?: string
          duration_minutes?: number
          color?: string
          price_cents?: number | null
          is_active?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "service_types_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          }
        ]
      }
      patients: {
        Row: {
          id: string
          clinic_id: string
          first_name: string
          last_name: string
          dni: string | null
          birth_date: string | null
          gender: string | null
          phone: string | null
          email: string | null
          address: string | null
          city: string | null
          postal_code: string | null
          notes_admin: string | null
          referred_by: string | null
          is_active: boolean
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          clinic_id: string
          first_name: string
          last_name: string
          dni?: string | null
          birth_date?: string | null
          gender?: string | null
          phone?: string | null
          email?: string | null
          address?: string | null
          city?: string | null
          postal_code?: string | null
          notes_admin?: string | null
          referred_by?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          clinic_id?: string
          first_name?: string
          last_name?: string
          dni?: string | null
          birth_date?: string | null
          gender?: string | null
          phone?: string | null
          email?: string | null
          address?: string | null
          city?: string | null
          postal_code?: string | null
          notes_admin?: string | null
          referred_by?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "patients_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          }
        ]
      }
      patient_accounts: {
        Row: {
          id: string
          clinic_id: string
          patient_id: string
          user_id: string
          invited_by: string | null
          invited_at: string
          accepted_at: string | null
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          patient_id: string
          user_id: string
          invited_by?: string | null
          invited_at?: string
          accepted_at?: string | null
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          patient_id?: string
          user_id?: string
          invited_by?: string | null
          invited_at?: string
          accepted_at?: string | null
          is_active?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "patient_accounts_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_accounts_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: true
            referencedRelation: "patients"
            referencedColumns: ["id"]
          }
        ]
      }
      clinic_consents: {
        Row: {
          id: string
          clinic_id: string
          kind: Database["public"]["Enums"]["consent_kind"]
          version: number
          title: string
          body_markdown: string
          is_current: boolean
          created_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          kind: Database["public"]["Enums"]["consent_kind"]
          version: number
          title: string
          body_markdown: string
          is_current?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          kind?: Database["public"]["Enums"]["consent_kind"]
          version?: number
          title?: string
          body_markdown?: string
          is_current?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "clinic_consents_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          }
        ]
      }
      patient_consents: {
        Row: {
          id: string
          patient_id: string
          clinic_id: string
          consent_id: string
          granted: boolean
          granted_at: string
          granted_ip: string | null
          granted_user_agent: string | null
          signature_image_url: string | null
          withdrawn_at: string | null
        }
        Insert: {
          id?: string
          patient_id: string
          clinic_id: string
          consent_id: string
          granted: boolean
          granted_at?: string
          granted_ip?: string | null
          granted_user_agent?: string | null
          signature_image_url?: string | null
          withdrawn_at?: string | null
        }
        Update: {
          id?: string
          patient_id?: string
          clinic_id?: string
          consent_id?: string
          granted?: boolean
          granted_at?: string
          granted_ip?: string | null
          granted_user_agent?: string | null
          signature_image_url?: string | null
          withdrawn_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "patient_consents_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_consents_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_consents_consent_id_fkey"
            columns: ["consent_id"]
            isOneToOne: false
            referencedRelation: "clinic_consents"
            referencedColumns: ["id"]
          }
        ]
      }
      appointments: {
        Row: {
          id: string
          clinic_id: string
          patient_id: string
          professional_id: string
          room_id: string | null
          service_type_id: string | null
          starts_at: string
          ends_at: string
          status: Database["public"]["Enums"]["appointment_status"]
          notes_for_reception: string | null
          cancel_reason: string | null
          cancelled_by: string | null
          cancelled_at: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          patient_id: string
          professional_id: string
          room_id?: string | null
          service_type_id?: string | null
          starts_at: string
          ends_at: string
          status?: Database["public"]["Enums"]["appointment_status"]
          notes_for_reception?: string | null
          cancel_reason?: string | null
          cancelled_by?: string | null
          cancelled_at?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          patient_id?: string
          professional_id?: string
          room_id?: string | null
          service_type_id?: string | null
          starts_at?: string
          ends_at?: string
          status?: Database["public"]["Enums"]["appointment_status"]
          notes_for_reception?: string | null
          cancel_reason?: string | null
          cancelled_by?: string | null
          cancelled_at?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "appointments_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_professional_id_fkey"
            columns: ["professional_id"]
            isOneToOne: false
            referencedRelation: "professionals"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_service_type_id_fkey"
            columns: ["service_type_id"]
            isOneToOne: false
            referencedRelation: "service_types"
            referencedColumns: ["id"]
          }
        ]
      }
      clinical_records: {
        Row: {
          id: string
          patient_id: string
          clinic_id: string
          chief_complaint: string | null
          diagnosis: string | null
          medical_history: string | null
          current_medication: string | null
          allergies: string | null
          red_flags: string | null
          objectives: string | null
          created_at: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          id?: string
          patient_id: string
          clinic_id: string
          chief_complaint?: string | null
          diagnosis?: string | null
          medical_history?: string | null
          current_medication?: string | null
          allergies?: string | null
          red_flags?: string | null
          objectives?: string | null
          created_at?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          id?: string
          patient_id?: string
          clinic_id?: string
          chief_complaint?: string | null
          diagnosis?: string | null
          medical_history?: string | null
          current_medication?: string | null
          allergies?: string | null
          red_flags?: string | null
          objectives?: string | null
          created_at?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "clinical_records_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: true
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "clinical_records_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          }
        ]
      }
      session_notes: {
        Row: {
          id: string
          clinic_id: string
          appointment_id: string
          clinical_record_id: string
          subjective: string | null
          objective: string | null
          assessment: string | null
          plan: string | null
          techniques: Json
          home_program: string | null
          pain_pre: number | null
          pain_post: number | null
          author_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          appointment_id: string
          clinical_record_id: string
          subjective?: string | null
          objective?: string | null
          assessment?: string | null
          plan?: string | null
          techniques?: Json
          home_program?: string | null
          pain_pre?: number | null
          pain_post?: number | null
          author_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          appointment_id?: string
          clinical_record_id?: string
          subjective?: string | null
          objective?: string | null
          assessment?: string | null
          plan?: string | null
          techniques?: Json
          home_program?: string | null
          pain_pre?: number | null
          pain_post?: number | null
          author_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "session_notes_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: true
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_notes_clinical_record_id_fkey"
            columns: ["clinical_record_id"]
            isOneToOne: false
            referencedRelation: "clinical_records"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "session_notes_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          }
        ]
      }
      documents: {
        Row: {
          id: string
          clinic_id: string
          patient_id: string
          kind: Database["public"]["Enums"]["document_kind"]
          filename: string
          mime: string
          size_bytes: number
          storage_path: string
          notes: string | null
          uploaded_by: string | null
          uploaded_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          patient_id: string
          kind?: Database["public"]["Enums"]["document_kind"]
          filename: string
          mime: string
          size_bytes: number
          storage_path: string
          notes?: string | null
          uploaded_by?: string | null
          uploaded_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          patient_id?: string
          kind?: Database["public"]["Enums"]["document_kind"]
          filename?: string
          mime?: string
          size_bytes?: number
          storage_path?: string
          notes?: string | null
          uploaded_by?: string | null
          uploaded_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "documents_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "documents_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          }
        ]
      }
      reminder_templates: {
        Row: {
          id: string
          clinic_id: string
          name: string
          channel: Database["public"]["Enums"]["reminder_channel"]
          subject_template: string | null
          body_template: string
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          name: string
          channel: Database["public"]["Enums"]["reminder_channel"]
          subject_template?: string | null
          body_template: string
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          name?: string
          channel?: Database["public"]["Enums"]["reminder_channel"]
          subject_template?: string | null
          body_template?: string
          is_active?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reminder_templates_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          }
        ]
      }
      appointment_reminders: {
        Row: {
          id: string
          clinic_id: string
          appointment_id: string
          template_id: string | null
          channel: Database["public"]["Enums"]["reminder_channel"]
          scheduled_at: string
          status: Database["public"]["Enums"]["reminder_status"]
          provider_message_id: string | null
          error_message: string | null
          sent_at: string | null
          payload_snapshot: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          clinic_id: string
          appointment_id: string
          template_id?: string | null
          channel: Database["public"]["Enums"]["reminder_channel"]
          scheduled_at: string
          status?: Database["public"]["Enums"]["reminder_status"]
          provider_message_id?: string | null
          error_message?: string | null
          sent_at?: string | null
          payload_snapshot?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          clinic_id?: string
          appointment_id?: string
          template_id?: string | null
          channel?: Database["public"]["Enums"]["reminder_channel"]
          scheduled_at?: string
          status?: Database["public"]["Enums"]["reminder_status"]
          provider_message_id?: string | null
          error_message?: string | null
          sent_at?: string | null
          payload_snapshot?: Json | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "appointment_reminders_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointment_reminders_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointment_reminders_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "reminder_templates"
            referencedColumns: ["id"]
          }
        ]
      }
      audit_logs: {
        Row: {
          id: number
          clinic_id: string | null
          actor_user_id: string | null
          action: Database["public"]["Enums"]["audit_action"]
          entity_type: string
          entity_id: string | null
          entity_owner_id: string | null
          metadata: Json
          ip: string | null
          user_agent: string | null
          at: string
        }
        Insert: {
          id?: number
          clinic_id?: string | null
          actor_user_id?: string | null
          action: Database["public"]["Enums"]["audit_action"]
          entity_type: string
          entity_id?: string | null
          entity_owner_id?: string | null
          metadata?: Json
          ip?: string | null
          user_agent?: string | null
          at?: string
        }
        Update: {
          id?: number
          clinic_id?: string | null
          actor_user_id?: string | null
          action?: Database["public"]["Enums"]["audit_action"]
          entity_type?: string
          entity_id?: string | null
          entity_owner_id?: string | null
          metadata?: Json
          ip?: string | null
          user_agent?: string | null
          at?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: { [k: string]: never }
    Functions: {
      bootstrap_clinic: {
        Args: {
          p_name: string
          p_legal_name?: string | null
          p_cif?: string | null
          p_address?: string | null
          p_city?: string | null
          p_postal_code?: string | null
          p_phone?: string | null
          p_email?: string | null
          p_timezone?: string
        }
        Returns: string
      }
      anonymize_patient: {
        Args: { p_patient_id: string }
        Returns: undefined
      }
      current_user_clinic_ids: {
        Args: Record<string, never>
        Returns: { clinic_id: string }[]
      }
      current_user_role: {
        Args: { target_clinic: string }
        Returns: Database["public"]["Enums"]["member_role"] | null
      }
      current_patient_ids: {
        Args: Record<string, never>
        Returns: { patient_id: string }[]
      }
      get_invitation_preview: {
        Args: { p_token: string }
        Returns: { email: string; role: "admin" | "physio" | "reception" }
      }
      accept_invitation: {
        Args: { p_token: string }
        Returns: string
      }
      search_patients: {
        Args: { p_clinic: string; p_query: string }
        Returns: { id: string; label: string }[]
      }
      write_audit_log: {
        Args: {
          p_action:
            | "view"
            | "create"
            | "update"
            | "delete"
            | "export"
            | "login"
            | "logout"
            | "consent_grant"
            | "consent_withdraw"
          p_entity_type: string
          p_entity_id?: string | null
          p_entity_owner_id?: string | null
          p_metadata?: Json
        }
        Returns: undefined
      }
    }
    Enums: {
      member_role: "admin" | "physio" | "reception"
      appointment_status:
        | "scheduled"
        | "confirmed"
        | "checked_in"
        | "completed"
        | "no_show"
        | "cancelled"
      room_kind: "consulta" | "box" | "gimnasio" | "otro"
      consent_kind: "tratamiento" | "comunicaciones" | "imagen" | "menores"
      reminder_channel: "email" | "inapp"
      reminder_status: "pending" | "sent" | "failed" | "cancelled"
      document_kind:
        | "informe"
        | "prueba_imagen"
        | "consentimiento"
        | "receta"
        | "otro"
      audit_action:
        | "view"
        | "create"
        | "update"
        | "delete"
        | "export"
        | "login"
        | "logout"
        | "consent_grant"
        | "consent_withdraw"
    }
    CompositeTypes: { [k: string]: never }
  }
}
